version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn app.main:app -c src/config/runtime/gunicorn.conf.py
    volumes:
      - .:/src
    ports:
      - "2000:2000"
    environment:
      - DB_URL=mongodb://mongo:27017
